### ISSUE TITLE
how use that library?

### ISSUE THREAD

**Issue by ghost** [JackNoordhuis/ext-pocketmine-math#1]
how can i compile pmmp with that library?

**Comment by JackNoordhuis** [comment]
The extension currently isn't finished and development won't continue until pocketmine moves away from using arrays in constants as it causes issues trying to define them through the extension. There are workarounds to this but I'd rather keep everything contained within the extension.

**Comment by JackNoordhuis** [comment]
As a side note if you feel like trying to use the extension anyway, you would compile like any other php extension: https://ma.ttias.be/how-to-compile-and-install-php-extensions-from-source/

**Comment by ghost** [comment]
Okey, thank you!
